USE [master]
GO

/****** Object:  Database [GenussRest]    Script Date: 31.01.2025 19:48:36 ******/

CREATE DATABASE [GenussRest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GenussRest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\GenussRest.mdf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'GenussRest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\GenussRest_log.ldf' , SIZE = 10240KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GenussRest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GenussRest] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GenussRest] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GenussRest] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GenussRest] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GenussRest] SET ARITHABORT OFF 
GO

ALTER DATABASE [GenussRest] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GenussRest] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GenussRest] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GenussRest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GenussRest] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GenussRest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GenussRest] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GenussRest] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GenussRest] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GenussRest] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GenussRest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GenussRest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GenussRest] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GenussRest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GenussRest] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GenussRest] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GenussRest] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GenussRest] SET RECOVERY FULL 
GO

ALTER DATABASE [GenussRest] SET  MULTI_USER 
GO

ALTER DATABASE [GenussRest] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GenussRest] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GenussRest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GenussRest] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GenussRest] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GenussRest] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [GenussRest] SET QUERY_STORE = ON
GO

ALTER DATABASE [GenussRest] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [GenussRest] SET  READ_WRITE 
GO


